### ISSUE TITLE
AttributeError with git line

### ISSUE THREAD

**Issue by kichik** [alanhamlett/pip-update-requirements#2]
The following line in my `requirements.txt` file causes pur to fail.

```
git+git://github.com/django-haystack/django-haystack.git@10bcc7668ccaab499f8db516fd59de182aadbcb4
```

The exception I get is:

```
Traceback (most recent call last):
  File "/home/amir/DEV/bin/pur", line 11, in <module>
    sys.exit(pur())
  File "/home/amir/DEV/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/amir/DEV/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/amir/DEV/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/amir/DEV/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/amir/DEV/lib/python3.5/site-packages/pur/__init__.py", line 44, in pur
    for line, req, spec_ver, latest_ver in requirements:
  File "/home/amir/DEV/lib/python3.5/site-packages/pur/__init__.py", line 90, in get_requirements_and_latest
    spec_ver = Version(req.req.specs[0][1])
AttributeError: 'NoneType' object has no attribute 'specs'
```

I'm on Python 3.5 with pip 8.1.1.

It seems like `req.req` is `None` for that kind of line. I was able to locally fix the issue by catching `AttributeError` on top of `IndexError`.

**Comment by kichik** [comment]
Thanks!
