### ISSUE TITLE
Error running with Python 3.10: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by lancelote** [alanhamlett/pip-update-requirements#39]
Running `pur -r requirements.txt ` with Python 3.10 environment raises

```
Traceback (most recent call last):
  File "/Users/.../.virtualenvs/test_pur_python310/bin/pur", line 5, in <module>
    from pur.__init__ import pur
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/__init__.py", line 37, in <module>
    from pip._internal.index import PackageFinder
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/cli/base_command.py", line 24, in <module>
    from pip._internal.index import PackageFinder
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_internal/index.py", line 14, in <module>
    from pip._vendor import html5lib, requests, six
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_vendor/html5lib/__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_vendor/html5lib/html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_vendor/html5lib/_tokenizer.py", line 16, in <module>
    from ._trie import Trie
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_vendor/html5lib/_trie/__init__.py", line 3, in <module>
    from .py import Trie as PyTrie
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_vendor/html5lib/_trie/py.py", line 6, in <module>
    from ._base import Trie as ABCTrie
  File "/Users/.../.virtualenvs/test_pur_python310/lib/python3.10/site-packages/pur/packages/pip/_vendor/html5lib/_trie/_base.py", line 3, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

The bundled version of `html5lib` is too old to be used with Python 3.10. The latest version [doesn't have this problem][1]. Should the vendored `pip` be upgraded? One can also directly patch vendored `html5lib` as a cheap fix.

[1]: https://github.com/pypa/pip/blob/156f71b5e8e7174e21d9f28dd809cf4bf5345eb8/src/pip/_vendor/html5lib/_trie/_base.py#L4

**Comment by alanhamlett** [comment]
Patched with ea9e52891b6a3caf9401727eddb581a9f4a54381 and released in v5.4.2. We should definitely upgrade the vendored pip, but not sure when I'll be able to do that.
