### ISSUE TITLE
Error with --index-url param

### ISSUE THREAD

**Issue by BolkoSchreiber** [alanhamlett/pip-update-requirements#64]
Using `pur` with `--index-url` does not work properly.

`pur -r requirements.txt --index-url https://some_gitlab_instance.com/path/to/package/registry`

```
Error: Traceback (most recent call last):
  File "[...]/venv/lib/python3.10/site-packages/pur/__init__.py", line 132, in pur
    update_requirements(
  File "[...]/venv/lib/python3.10/site-packages/pur/__init__.py", line 201, in update_requirements
    _update_requirements(
  File "[...]/venv/lib/python3.10/site-packages/pur/__init__.py", line 269, in _update_requirements
    for line, req, spec_ver, latest_ver in requirements:
  File "[...]/venv/lib/python3.10/site-packages/pur/__init__.py", line 389, in _get_requirements_and_latest
    for parsed_req, orig_line in requirements:
  File "[...]/venv/lib/python3.10/site-packages/pur/__init__.py", line 440, in _parse_requirements
    parsed_req = handle_line(
  File "[...]/venv/lib/python3.10/site-packages/pur/packages/pip/_internal/req/req_file.py", line 311, in handle_line
    handle_option_line(
  File "[...]/venv/lib/python3.10/site-packages/pur/packages/pip/_internal/req/req_file.py", line 243, in handle_option_line
AttributeError: 'tuple' object has no attribute 'extend'
```

**Comment by BolkoSchreiber** [comment]
nvm ... i was beeing stupid ....
